package com.pureblue.woad.ui;

import com.pureblue.woad.mixin.FontAccessor;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.Font;
import net.minecraft.client.gui.GlyphSource;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.font.glyphs.EffectGlyph;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.FontDescription;
import net.minecraft.resources.Identifier;
import net.minecraft.util.FormattedCharSequence;

import java.util.List;

/**
 * Text in Woad's screens, set in Inter.
 *
 * <p>Minecraft samples TrueType glyphs without filtering, so text is only sharp when its glyphs
 * were rasterised at exactly the on-screen density. The mod therefore ships one font definition
 * per style and per GUI scale ({@code assets/woad/font/ui/<style>_<scale>.json}, oversample =
 * scale, generated by {@code tools/make_fonts.py}), and the right one is picked at draw time.
 * Changing the GUI scale needs no reload.
 *
 * <p>Each style is exposed as a real {@link Font}: a thin wrapper that answers every request for
 * the default font with Inter. Measuring, wrapping, truncating and drawing therefore all agree,
 * and so does anything the game itself does with that Font — a text field's cursor and selection
 * included. The chat and the rest of the game keep Minecraft's own font.
 *
 * <p>Positions are given as the top of the capital letters, not as a line box: {@link #centerY}
 * returns exactly that, and drawing converts it to where Minecraft wants the line.
 */
public final class UiText {

    private UiText() {}

    /** Rasterisations shipped: 1x to 8x. Denser scales reuse the 8x one. */
    private static final int MAX_SCALE = 8;

    /**
     * Minecraft sets a TrueType line's baseline this far below the y it is drawn at, whatever the
     * font size — measured in game. Knowing it is what lets text be centred on its capitals.
     */
    private static final float BASELINE = 7f;

    /** Inter's capital height, as a fraction of its em. */
    private static final float CAP_RATIO = 0.727f;

    public enum Style {
        /** 11 px bold: the screen title. */
        TITLE("title", 14, 11f, 11f),
        /** 10.5 px semibold: a section or feature title. */
        HEADING("heading", 13, 10.5f, 10.5f),
        /** 7.5 px semibold (8 at GUI scale 1): setting names, buttons, emphasis. */
        LABEL("label", 10, 7.5f, 8f),
        /** 7 px regular (8 at GUI scale 1): descriptions and values. */
        BODY("body", 10, 7f, 8f);

        final String id;
        /** Distance between two wrapped lines, in GUI pixels. */
        public final int lineHeight;
        private final float em;
        /** At GUI scale 1 a pixel is a pixel, and the smallest sizes grow to stay readable. */
        private final float emAtScale1;
        private final FontDescription[] descriptions = new FontDescription[MAX_SCALE + 1];
        private Font font;

        Style(String id, int lineHeight, float em, float emAtScale1) {
            this.id = id;
            this.lineHeight = lineHeight;
            this.em = em;
            this.emAtScale1 = emAtScale1;
        }

        FontDescription description() {
            int scale = oversample();
            FontDescription d = descriptions[scale];
            if (d == null) {
                d = new FontDescription.Resource(Identifier.fromNamespaceAndPath("woad", "ui/" + id + "_" + scale));
                descriptions[scale] = d;
            }
            return d;
        }

        /** Em size of the rasterisation in use. Keep in sync with {@code make_fonts.py}. */
        float em() {
            return oversample() == 1 ? emAtScale1 : em;
        }
    }

    /**
     * Which rasterisation to use: the one whose pixel density matches the screen here, GUI scale
     * and any extra magnification ({@link Draw#pushScale}) together.
     */
    private static int oversample() {
        return Math.max(1, Math.min(MAX_SCALE, Math.round(Draw.effectiveScale())));
    }

    /**
     * The Font for a style. Hand it to anything that takes a Font — an {@code EditBox} included —
     * and it will lay out and draw in Inter.
     */
    public static Font font(Style style) {
        if (style.font == null) {
            Font.Provider game = ((FontAccessor) Minecraft.getInstance().font).woad$provider();
            style.font = new Font(new Font.Provider() {
                @Override
                public GlyphSource glyphs(FontDescription description) {
                    // Only the default font is swapped: explicit fonts (the enchanting alphabet,
                    // sprites in text) stay what they asked to be.
                    return game.glyphs(FontDescription.DEFAULT.equals(description) ? style.description() : description);
                }

                @Override
                public EffectGlyph effect() {
                    return game.effect();
                }
            });
        }
        return style.font;
    }

    // ---- Measuring -------------------------------------------------------------------------------

    public static int width(String text, Style style) {
        return font(style).width(text);
    }

    public static int width(Component text, Style style) {
        return font(style).width(text);
    }

    public static int width(FormattedCharSequence text, Style style) {
        return font(style).width(text);
    }

    /** Cuts {@code text} with an ellipsis so it fits {@code maxWidth}. */
    public static String ellipsize(String text, Style style, int maxWidth) {
        Font f = font(style);
        if (f.width(text) <= maxWidth) return text;
        String dots = "…";
        int room = Math.max(0, maxWidth - f.width(dots));
        return f.plainSubstrByWidth(text, room).stripTrailing() + dots;
    }

    public static List<FormattedCharSequence> wrap(String text, Style style, int maxWidth) {
        return font(style).split(Component.literal(text), Math.max(1, maxWidth));
    }

    /** Height a wrapped paragraph will take. */
    public static int wrappedHeight(String text, Style style, int maxWidth) {
        return wrap(text, style, maxWidth).size() * style.lineHeight;
    }

    /** Height of the capital letters at the current GUI scale. */
    public static float capHeight(Style style) {
        return style.em() * CAP_RATIO;
    }

    /** Where the capitals of a single line start so the line sits centred in a box. */
    public static float centerY(Style style, float boxY, float boxH) {
        return boxY + (boxH - capHeight(style)) / 2f;
    }

    /**
     * The y to hand Minecraft so the capitals start at {@code capTop}: its baseline sits
     * {@link #BASELINE} below the y it is given.
     */
    public static float lineY(Style style, float capTop) {
        return capTop - BASELINE + capHeight(style);
    }

    // ---- Drawing ---------------------------------------------------------------------------------

    /** Draws a line with its capitals starting at {@code y}. */
    public static void draw(GuiGraphicsExtractor ctx, String text, Style style, float x, float y, int color) {
        draw(ctx, FormattedCharSequence.forward(text, net.minecraft.network.chat.Style.EMPTY), style, x, y, color);
    }

    public static void draw(GuiGraphicsExtractor ctx, Component text, Style style, float x, float y, int color) {
        draw(ctx, text.getVisualOrderText(), style, x, y, color);
    }

    public static void draw(GuiGraphicsExtractor ctx, FormattedCharSequence text, Style style, float x, float y, int color) {
        draw(ctx, text, style, x, y, color, false);
    }

    /**
     * Draws a line, optionally with the game's drop shadow — which is what keeps light colours
     * readable on a light background (the colour-code reference relies on it).
     */
    public static void draw(GuiGraphicsExtractor ctx, FormattedCharSequence text, Style style, float x, float y,
                            int color, boolean shadow) {
        int colour = Draw.fade(color);
        if (((colour >>> 24) & 0xFF) == 0) return;
        // The game places text on whole GUI pixels; at GUI scale 2 and up that wastes precision a
        // screen pixel could give. Snap to the nearest physical pixel and carry the fraction in
        // the pose, so centring is exact and glyphs still land on pixel boundaries.
        float scale = Draw.effectiveScale();
        float px = Math.round(x * scale) / scale;
        float py = Math.round(lineY(style, y) * scale) / scale;
        int ix = (int) Math.floor(px);
        int iy = (int) Math.floor(py);
        float fx = px - ix;
        float fy = py - iy;
        if (fx == 0f && fy == 0f) {
            ctx.text(font(style), text, ix, iy, colour, shadow);
            return;
        }
        ctx.pose().pushMatrix();
        ctx.pose().translate(fx, fy);
        ctx.text(font(style), text, ix, iy, colour, shadow);
        ctx.pose().popMatrix();
    }

    public static void drawCentered(GuiGraphicsExtractor ctx, String text, Style style, float cx, float y, int color) {
        draw(ctx, text, style, cx - width(text, style) / 2f, y, color);
    }

    /** Draws a wrapped paragraph, capitals of the first line at {@code y}, and returns its height. */
    public static int drawWrapped(GuiGraphicsExtractor ctx, String text, Style style, float x, float y,
                                  int maxWidth, int color) {
        List<FormattedCharSequence> lines = wrap(text, style, maxWidth);
        for (int i = 0; i < lines.size(); i++) {
            draw(ctx, lines.get(i), style, x, y + i * style.lineHeight, color);
        }
        return lines.size() * style.lineHeight;
    }
}
